spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
  thymeleaf:
    prefix: classpath:/static/


  mail:
    # Google smtp server 사용
    host: smtp.gmail.com
    port: 587
    username: baesoomin6
    password: pgbchucoclqozqxx
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true



